Feature branch
akezeth/Metrics-webapp pull request #1
Opened 2023-07-05 15:48 UTC by akezeth

- Used React documentation.
- Used React components.
- Used React props.
- Used React Router.
- Connected React and Redux.
- Handled events in a React app.
- Wrote integration tests with a React testing library.
- Used styles in a React app.
- Used React life cycle methods.
- Applied React best practices and language style guides in code.
- Used store, actions and reducers in React.

Presentation link:

2023-07-05 18:50 UTC, Munsa1 requested changes
Hi @akezeth, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
## Highlight
Good Video Presentation ✔️ 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-07-05 18:50 UTC, Munsa1 commented on src/components/CryptoCurrency.js
> +                        {Math.abs(changePercent24Hr).toFixed(2)}
- [ ] It is a requirement that we should follow the design guidelines including the :
- typography: font face, size, and weight
- Layout: composition and space between elements.

Kindly change the font-family to either lato or gill-sans

2023-07-05 18:50 UTC, Munsa1 commented on src/__tests__/CryptoCurrency.test.js
> +jest.mock('react-redux');
- [ ] Good job adding tests for the `CryptoCurrency` page, kindly do so for the `Details` page as well as this is a requirement to test several components of our app.

2023-07-07 13:54 UTC, akezeth commented
- Changed the font-family to Lato.
- Added test for the Details component.

2023-07-07 14:26 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @akezeth 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Descriptive PR.
- Good commit messages.
- Correct git-flow.

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-07 18:22 UTC, merged